services:
  webapp:
    image: productapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Map port 80 in the container to port 5000 on the host
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Serverdb;Database=Product;Trusted_Connection=True;TrustServerCertificate=True;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
